---
abstract: 'attribute-oriented server/client object remoting framework'
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
build_requires:
  Test::Exception: 0
  Test::HexString: 0
  Test::Identity: 0
  Test::Memory::Cycle: 0
  Test::More: 0
  Test::Refcount: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tangence
provides:
  Net::Async::Tangence::Client:
    file: lib/Net/Async/Tangence/Client.pm
    version: 0.03
  Net::Async::Tangence::Protocol:
    file: lib/Net/Async/Tangence/Protocol.pm
    version: 0.03
  Net::Async::Tangence::Server:
    file: lib/Net/Async/Tangence/Server.pm
    version: 0.03
  Net::Async::Tangence::ServerContext:
    file: lib/Net/Async/Tangence/ServerContext.pm
    version: 0.03
  Net::Async::Tangence::ServerProtocol:
    file: lib/Net/Async/Tangence/ServerProtocol.pm
    version: 0.03
  Tangence:
    file: lib/Tangence.pm
    version: 0.03
  Tangence::Constants:
    file: lib/Tangence/Constants.pm
    version: 0.03
  Tangence::Message:
    file: lib/Tangence/Message.pm
    version: 0.03
  Tangence::Meta::Class:
    file: lib/Tangence/Meta/Class.pm
    version: 0.03
  Tangence::Metacode:
    file: lib/Tangence/Metacode.pm
    version: 0.03
  Tangence::Object:
    file: lib/Tangence/Object.pm
    version: 0.03
  Tangence::ObjectProxy:
    file: lib/Tangence/ObjectProxy.pm
    version: 0.03
  Tangence::Registry:
    file: lib/Tangence/Registry.pm
    version: 0.03
requires:
  Encode: 0
  IO::Async::Listener: 0.36
  IO::Async::Loop: 0.16
  IO::Async::Protocol::Stream: 0
  IO::Async::Stream: 0
  IO::Async::Test: 0
  URI::Split: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.03
